// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { expand } from "dotenv-expand";

const envConfig = config();
expand(envConfig);

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "src/infrastructure/database/prisma/schema.prisma",
  migrations: {
    path: "src/infrastructure/database/prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
